import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.scss";

export const metadata: Metadata = {
  title: "tuanpc1902",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body >
        <AntdRegistry>{children}</AntdRegistry>
    </body>
  </html>
);

export default RootLayout;